"""Base commit

Revision ID: 6707c66f91de
Revises: e3013f820413
Create Date: 2025-10-10 16:18:50.517651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "6707c66f91de"
down_revision: Union[str, Sequence[str], None] = "e3013f820413"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # CREATE THE ENUM TYPE FIRST WITH SAFETY CHECK
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'priority') THEN
                CREATE TYPE priority AS ENUM ('high_priority', 'mid_priority', 'low_priority');
            END IF;
        END
        $$;
    """)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "project_name",
            sa.String(length=128),
            server_default="project_name",
            nullable=False,
        ),
        sa.Column(
            "start_date", sa.String(), server_default="2025-10-10", nullable=False
        ),
        sa.Column("end_date", sa.String(), server_default="2025-10-10", nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "first_name", sa.String(length=32), server_default="", nullable=False
        ),
        sa.Column("last_name", sa.String(length=32), server_default="", nullable=False),
        sa.Column("salary", sa.Integer(), nullable=False),
        sa.Column("is_working", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_description", sa.String(), server_default="", nullable=False),
        sa.Column(
            "start_date", sa.String(), server_default="2025-10-10", nullable=False
        ),
        sa.Column("end_date", sa.String(), server_default="2025-10-10", nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "priority",
            ENUM(
                "high_priority",
                "mid_priority",
                "low_priority",
                name="priority",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "tasks_employees",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "employee_id"),
    )

    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_info", sa.String(), server_default="", nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "user_password",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sa.String(), server_default="", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )

    op.drop_table("models")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала удаляем таблицы, которые зависят от других
    op.drop_table("user_password", if_exists=True)
    op.drop_table("notes", if_exists=True)
    op.drop_table("tasks_employees", if_exists=True)

    # Затем удаляем основные таблицы
    op.drop_table("tasks", if_exists=True)
    op.drop_table("employees", if_exists=True)
    op.drop_table("projects", if_exists=True)

    # И только потом удаляем тип
    op.execute("DROP TYPE IF EXISTS priority")
    # op.execute("DROP TYPE priority")

    op.create_table(
        "models",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("models_pkey")),
    )
    # ### end Alembic commands ###
