"""adding data

Revision ID: f5d761324243
Revises: 6707c66f91de
Create Date: 2025-10-10 16:36:11.403997

"""

from typing import Sequence, Union

from sqlalchemy.orm import Session

from alembic import op
from relation.services.data_helper import add_data_into_db_sync, get_data_sync

# from sqlalchemy import table, column, String, Integer

# revision identifiers, used by Alembic.
revision: str = "f5d761324243"
down_revision: Union[str, Sequence[str], None] = "6707c66f91de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    data = get_data_sync()
    bind = op.get_bind()
    session = Session(bind=bind)

    add_data_into_db_sync(data, session)
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM user_password")
    op.execute("DELETE FROM notes")
    op.execute("DELETE FROM tasks_employees")

    # Затем удаляем основные таблицы
    op.execute("DELETE FROM tasks")
    op.execute("DELETE FROM employees")
    op.execute("DELETE FROM projects")

    # ### end Alembic commands ###
