"""initial commit

Revision ID: e3013f820413
Revises:
Create Date: 2025-10-10 16:06:14.746173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3013f820413"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.execute("DROP TABLE tasks CASCADE")
    # op.execute("DROP TABLE employees CASCADE")
    # op.execute("DROP TABLE tasks_employees CASCADE")
    # op.execute("DROP TABLE projects CASCADE")
    # op.execute("DROP TABLE notes CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     "tasks",
    #     sa.Column(
    #         "id",
    #         sa.INTEGER(),
    #         server_default=sa.text("nextval('tasks_id_seq'::regclass)"),
    #         autoincrement=True,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "task_description", sa.VARCHAR(), autoincrement=False, nullable=False
    #     ),
    #     sa.Column(
    #         "start_date",
    #         sa.VARCHAR(),
    #         server_default=sa.text("'2025-09-25'::character varying"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "end_date",
    #         sa.VARCHAR(),
    #         server_default=sa.text("'2025-09-25'::character varying"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "priority",
    #         postgresql.ENUM(
    #             "high_priority", "mid_priority", "low_priority", name="priority"
    #         ),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(
    #         ["project_id"],
    #         ["projects.id"],
    #         name="tasks_project_id_fkey",
    #         ondelete="CASCADE",
    #     ),
    #     sa.PrimaryKeyConstraint("id", name="tasks_pkey"),
    #     postgresql_ignore_search_path=False,
    # )
    # op.create_table(
    #     "employees",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("salary", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("is_working", sa.BOOLEAN(), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("id", name=op.f("employees_pkey")),
    # )
    # op.create_table(
    #     "tasks_employees",
    #     sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(
    #         ["employee_id"],
    #         ["employees.id"],
    #         name=op.f("tasks_employees_employee_id_fkey"),
    #         ondelete="CASCADE",
    #     ),
    #     sa.ForeignKeyConstraint(
    #         ["task_id"],
    #         ["tasks.id"],
    #         name=op.f("tasks_employees_task_id_fkey"),
    #         ondelete="CASCADE",
    #     ),
    #     sa.PrimaryKeyConstraint(
    #         "task_id", "employee_id", name=op.f("tasks_employees_pkey")
    #     ),
    # )
    # op.create_table(
    #     "projects",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("project_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         "start_date",
    #         sa.VARCHAR(),
    #         server_default=sa.text("'2025-09-25'::character varying"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "end_date",
    #         sa.VARCHAR(),
    #         server_default=sa.text("'2025-09-25'::character varying"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("id", name=op.f("projects_pkey")),
    # )
    # op.create_table(
    #     "notes",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("note_info", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(
    #         ["employee_id"],
    #         ["employees.id"],
    #         name=op.f("notes_employee_id_fkey"),
    #         ondelete="CASCADE",
    #     ),
    #     sa.ForeignKeyConstraint(
    #         ["task_id"],
    #         ["tasks.id"],
    #         name=op.f("notes_task_id_fkey"),
    #         ondelete="CASCADE",
    #     ),
    #     sa.PrimaryKeyConstraint("id", name=op.f("notes_pkey")),
    # )
    op.drop_table("models")
    # ### end Alembic commands ###
