"""Base commit

Revision ID: 6707c66f91de
Revises: e3013f820413
Create Date: 2025-10-10 16:18:50.517651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6707c66f91de"
down_revision: Union[str, Sequence[str], None] = "e3013f820413"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust!
    op.execute(
        "CREATE TYPE priority AS ENUM ('low_priority', 'mid_priority', 'high_priority')"
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "project_name",
            sa.String(length=128),
            server_default="project_name",
            nullable=False,
        ),
        sa.Column(
            "start_date", sa.String(), server_default="2025-10-10", nullable=False
        ),
        sa.Column("end_date", sa.String(), server_default="2025-10-10", nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_description", sa.String(), server_default="", nullable=False),
        sa.Column(
            "start_date", sa.String(), server_default="2025-10-10", nullable=False
        ),
        sa.Column("end_date", sa.String(), server_default="2025-10-10", nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("tasks") as batch_op:
        batch_op.add_column(
            sa.Column(
                "priority",
                sa.Enum(
                    "high_priority", "mid_priority", "low_priority", name="priority"
                ),
                nullable=False,
            )
        )

    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "first_name", sa.String(length=32), server_default="", nullable=False
        ),
        sa.Column("last_name", sa.String(length=32), server_default="", nullable=False),
        sa.Column("salary", sa.Integer(), nullable=False),
        sa.Column("is_working", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks_employees",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "employee_id"),
    )

    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_info", sa.String(), server_default="", nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.drop_table("models")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE priority")
    op.create_table(
        "models",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("models_pkey")),
    )
    op.drop_table("projects")
    op.drop_table("tasks")
    op.drop_table("employees")
    op.drop_table("tasks_employees")
    op.drop_table("notes")
    # ### end Alembic commands ###
